import React from "react";

export default function CountryDatalist() {
  return (
    <datalist id="countries">
      <option value="Afghanistan" />
      <option value="Albania" />
      <option value="Algeria" />
      <option value="Andorra" />
      <option value="Angola" />
      <option value="Anguilla" />
      <option value="Antarctica" />
      <option value="Argentina" />
      <option value="Armenia" />
      <option value="Aruba" />
      <option value="Australia" />
      <option value="Austria" />
      <option value="Azerbaijan" />
      <option value="Bahamas" />
      <option value="Bahrain" />
      <option value="Bangladesh" />
      <option value="Barbados" />
      <option value="Belarus" />
      <option value="Belgium" />
      <option value="Belize" />
      <option value="Benin" />
      <option value="Bermuda" />
      <option value="Bhutan" />
      <option value="Bolivia" />
      <option value="Botswana" />
      <option value="Brazil" />
      <option value="Bulgaria" />
      <option value="Burundi" />
      <option value="Cambodia" />
      <option value="Cameroon" />
      <option value="Canada" />
      <option value="Cape Verde" />
      <option value="Chad" />
      <option value="Chile" />
      <option value="China" />
      <option value="Colombia" />
      <option value="Comoros" />
      <option value="Congo" />
      <option value="Costa Rica" />
      <option value="Croatia" />
      <option value="Cuba" />
      <option value="Cyprus" />
      <option value="Czech Republic" />
      <option value="Denmark" />
      <option value="Djibouti" />
      <option value="Dominica" />
      <option value="Dominican Republic" />
      <option value="Ecuador" />
      <option value="Egypt" />
      <option value="El Salvador" />
      <option value="Equatorial Guinea" />
      <option value="Eritrea" />
      <option value="Estonia" />
      <option value="Ethiopia" />
      <option value="Faroe Islands" />
      <option value="Fiji" />
      <option value="Finland" />
      <option value="France" />
      <option value="Gabon" />
      <option value="Gambia" />
      <option value="Georgia" />
      <option value="Germany" />
      <option value="Ghana" />
      <option value="Gibraltar" />
      <option value="Greece" />
      <option value="Greenland" />
      <option value="Grenada" />
      <option value="Guadeloupe" />
      <option value="Guam" />
      <option value="Guatemala" />
      <option value="Guinea" />
      <option value="Guinea-bissau" />
      <option value="Guyana" />
      <option value="Haiti" />
      <option value="Honduras" />
      <option value="Hong Kong" />
      <option value="Hungary" />
      <option value="Iceland" />
      <option value="India" />
      <option value="Indonesia" />
      <option value="Iraq" />
      <option value="Ireland" />
      <option value="Israel" />
      <option value="Italy" />
      <option value="Jamaica" />
      <option value="Japan" />
      <option value="Jordan" />
      <option value="Kazakhstan" />
      <option value="Kenya" />
      <option value="Kiribati" />
      <option value="Republic of Korea" />
      <option value="Kuwait" />
      <option value="Kyrgyzstan" />
      <option value="Latvia" />
      <option value="Lebanon" />
      <option value="Lesotho" />
      <option value="Liberia" />
      <option value="Liechtenstein" />
      <option value="Lithuania" />
      <option value="Luxembourg" />
      <option value="Macao" />
      <option value="Madagascar" />
      <option value="Malawi" />
      <option value="Malaysia" />
      <option value="Maldives" />
      <option value="Mali" />
      <option value="Malta" />
      <option value="Marshall Islands" />
      <option value="Martinique" />
      <option value="Mauritania" />
      <option value="Mauritius" />
      <option value="Mayotte" />
      <option value="Mexico" />
      <option value="Republic of Moldova" />
      <option value="Monaco" />
      <option value="Mongolia" />
      <option value="Montserrat" />
      <option value="Morocco" />
      <option value="Mozambique" />
      <option value="Myanmar" />
      <option value="Namibia" />
      <option value="Nauru" />
      <option value="Nepal" />
      <option value="Netherlands" />
      <option value="New Caledonia" />
      <option value="New Zealand" />
      <option value="Nicaragua" />
      <option value="Niger" />
      <option value="Nigeria" />
      <option value="Niue" />
      <option value="Norfolk Island" />
      <option value="Northern Mariana Islands" />
      <option value="Norway" />
      <option value="Oman" />
      <option value="Pakistan" />
      <option value="Palau" />
      <option value="Panama" />
      <option value="Special Region of Papua" />
      <option value="Paraguay" />
      <option value="Peru" />
      <option value="Philippines" />
      <option value="Pitcairn" />
      <option value="Poland" />
      <option value="Portugal" />
      <option value="Puerto Rico" />
      <option value="Qatar" />
      <option value="Reunion" />
      <option value="Romania" />
      <option value="Russian" />
      <option value="Rwanda" />
      <option value="Samoa" />
      <option value="Saudi Arabia" />
      <option value="Senegal" />
      <option value="Serbia" />
      <option value="Montenegro" />
      <option value="Seychelles" />
      <option value="Sierra Leone" />
      <option value="Singapore" />
      <option value="Slovakia" />
      <option value="Slovenia" />
      <option value="Solomon Islands" />
      <option value="Somalia" />
      <option value="South Africa" />
      <option value="Spain" />
      <option value="Sri Lanka" />
      <option value="Sudan" />
      <option value="Suriname" />
      <option value="Eswatini" />
      <option value="Sweden" />
      <option value="Switzerland" />
      <option value="Syrian Arab Republic" />
      <option value="Taiwan" />
      <option value="Tajikistan" />
      <option value="Tanzania" />
      <option value="Thailand" />
      <option value="Timor-Leste" />
      <option value="Togo" />
      <option value="Tokelau" />
      <option value="Tonga" />
      <option value="Tunisia" />
      <option value="Turkey" />
      <option value="Turkmenistan" />
      <option value="Tuvalu" />
      <option value="Uganda" />
      <option value="Ukraine" />
      <option value="United Arab Emirates" />
      <option value="United Kingdom" />
      <option value="United States" />
      <option value="Uruguay" />
      <option value="Uzbekistan" />
      <option value="Vanuatu" />
      <option value="Venezuela" />
      <option value="Viet Nam" />
      <option value="Wallis" />
      <option value="Sahara" />
      <option value="Yemen" />
      <option value="Zambia" />
      <option value="Zimbabwe" />
    </datalist>
  );
}
